### ISSUE TITLE
`ans` not defined

### ISSUE THREAD

**Issue by bojohnson5** [rm-dr/daisy#3]
I have v1.0.1 installed on MacOS 12.6.9 from cargo. I'm running `daisy` in iTerm2 and not having the ability to use `ans` and the last answer.
![Screen Shot 2023-09-20 at 12 02 39 PM](https://github.com/rm-dr/daisy/assets/20647190/5be934a2-e8f0-4ea0-ae28-f9590eb480d3)

**Comment by rm-dr** [comment]
Just published a fix. Should work with `v1.1.0`.

Thanks for the catch!
