### ISSUE TITLE
first key typed isn't read

### ISSUE THREAD

**Issue by bojohnson5** [rm-dr/daisy#5]
Great project! Super useful for quick calculations using units! Same setup as before, MacOS Monterey with iTerm2. When first starting `daisy` and typing, the first character I type isn't read. See the image as an example. I was typing `help`. Things will work after this first key isn't read.
![Screen Shot 2023-09-20 at 2 45 27 PM](https://github.com/rm-dr/daisy/assets/20647190/2572381c-b305-4edc-a29e-2db15faaabd1)

**Comment by rm-dr** [comment]
Does this happen if you wait a bit after starting the app?
The terminal library I'm using takes a while to detect color support.

**Comment by bojohnson5** [comment]
If I wait it does look like it works properly, that's good to know!
